CREATE DATABASE IF NOT EXISTS devqueue;
USE devqueue;

CREATE TABLE IF NOT EXISTS User(
idx INT UNSIGNED AUTO_INCREMENT NOT NULL,
id VARCHAR(20) NOT NULL,
password BLOB NOT NULL,
name VARCHAR(20) NOT NULL,
mail VARCHAR(320) NOT NULL,
creation_date DATETIME NOT NULL,
PRIMARY KEY (idx)
);

CREATE TABLE IF NOT EXISTS Role(
id TINYINT UNSIGNED AUTO_INCREMENT NOT NULL,
role VARCHAR(15) NOT NULL UNIQUE,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Game(
id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
game_id VARCHAR(32) UNIQUE NOT NULL,
user_idx INT UNSIGNED NOT NULL,
nickname VARCHAR(20) NOT NULL,
role TINYINT UNSIGNED NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (user_idx) REFERENCES `User`(idx),
FOREIGN KEY (role) REFERENCES `Role`(id)
);

CREATE TABLE IF NOT EXISTS Log(
id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
game_id VARCHAR(32) UNIQUE NOT NULL,
log JSON NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (game_id) REFERENCES `Game`(game_id)
);
