CREATE DATABASE IF NOT EXISTS devqueue;
USE devqueue;

CREATE TABLE IF NOT EXISTS User(
idx INT UNSIGNED AUTO_INCREMENT NOT NULL,
id VARCHAR(20) NOT NULL,
password BLOB NOT NULL,
name VARCHAR(20) NOT NULL,
mail VARCHAR(320) NOT NULL,
creation_date DATETIME NOT NULL,
PRIMARY KEY (idx)
);

CREATE TABLE IF NOT EXISTS Role(
id TINYINT UNSIGNED AUTO_INCREMENT NOT NULL,
role VARCHAR(15) NOT NULL UNIQUE,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Game(
id VARCHAR(40) UNIQUE NOT NULL,
log JSON NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Record(
id VARCHAR(64) UNIQUE NOT NULL,
game_id VARCHAR(40) NOT NULL,
user_id INT UNSIGNED NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (game_id) REFERENCES Game(id),
FOREIGN KEY (user_id) REFERENCES User(idx)
);
